create or replace ICEBERG TABLE MY_ICEBERG_DB.PUBLIC.CCT_UDB26954 (
	POINT_ID DECIMAL(10, 0),
	TRAIL_NAME STRING,
	COORD_PAIR STRING,
	DISTANCE_TO_MELANIES DECIMAL(20, 10),
	USER_NAME STRING
)
 EXTERNAL_VOLUME = 'ICEBERG_EXTERNAL_VOLUME'
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'CCT_UDB26954/';