--Run this prior to lesson 4 or it will mess you up.
USE ROLE ORGADMIN;
Select SYSTEM
$ENABLE_GLOBAL_DATA_SHARING_FOR_ACCOUNT('VKB59192');


SELECT SYSTEM$IS_GLOBAL_DATA_SHARING_ENABLED_FOR_ACCOUNT('VKB59192');